// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azoxkxfaknkrdnfikbtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6b3hreGZha25rcmRuZmlrYnR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5ODIzODUsImV4cCI6MjA2NzU1ODM4NX0.ynAh6gU5SCoSjdwibsqDTWPM8ajfzUDLvM-gDBqga_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});